apiVersion: v1
kind: Service
metadata:
  name: internal-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snet-aks-public-southeastasia-001"
spec:
  type: LoadBalancer
  # loadBalancerIP: 10.20.20.20
  ports:
  - port: 80
  selector:
    app: aks-helloworld-one